# Generated by Django 4.2.27 on 2026-01-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_case_name', models.CharField(max_length=100)),
                ('uce_name', models.CharField(max_length=100)),
                ('tower', models.CharField(max_length=100)),
                ('task_type', models.CharField(max_length=100)),
                ('time_to_complete', models.DecimalField(decimal_places=2, help_text='Hours', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
